### ISSUE TITLE
Latest release is not available on PyPi...

### ISSUE THREAD

**Issue by corebyte** [mollie/mollie-api-python#11]
Latest 3 releases are not available on PyPi...

pip install --upgrade mollie-api-python results in no updates.. and i run 1.0.0 still.

**Comment by koenkarsten** [comment]
+1

**Comment by mollierobbert** [comment]
The latest release can be found on pip: https://pypi.python.org/pypi/mollie-api-python

I'll check to make sure we push the update to pip faster next time.
