### ISSUE TITLE
Order with pending payment

### ISSUE THREAD

**Issue by dmalis** [mollie/mollie-api-python#129]
I'm using orders api.

According to this diagram https://assets.docs.mollie.com/_images/payment-status-flow@2x.png a pending payment can continue only to paid / authorized state.

Is it safe to assume mollie order with pending payment (PAYPAL) will proceed to paid/authorized in the future and can be considered as "successfully paid" and ship items to the customer today?

If **yes**, how should we handle order.create_shipment() as mollie order can't be shipped from created state?

If **no**, how should we communicate this with customer? Since I'm seeing payments to pend for more than 24hrs, we can't expect user to look at refreshing "please wait" page for more than 15 seconds.

**Comment by whyscream** [comment]
Hi, this is more a generic Mollie question than something directly related to the python client. I can't really say anything useful about the processing speed of Paypal transactions. Maybe you, @ndijkstra ?

**Comment by ndijkstra** [comment]
Hi @dmalis, when a payment or order is pending it's not save yet to ship your order. We are still waiting on a OK from the supplier.

**Comment by dmalis** [comment]
Thank you @ndijkstra for prompt answer.

I can see some PayPal transactions are in pending state for more than 48hrs now. If I understand flow correct it goes like this:

user checks out with PP -> user is redirected to PP (order=created, payment=open) -> user completes the payment with PP (order=created, payment=pending) -> user is returned to our website

At this point, order has been placed, payment (from customers point of view) sent, but we can't ship it our for 12-48-X hrs. On top of that, I presume, payment can still be rejected by PP after 20hrs.

What is best practice for this situation? Reloading on "Please wait while processing" page is not working, payment is not complete either.

**Comment by ndijkstra** [comment]
@dmalis Can you contact our [support](https://www.mollie.com/en/contact) about this issue? It looks like there is something wrong with the [rights](https://help.mollie.com/hc/en-us/articles/213856625) in your PayPal account.

**Comment by dmalis** [comment]
Got it @ndijkstra , although this problem exists with only 1% of PP payments .. it happens with Przewly24 too.
