### ISSUE TITLE
Get customer_mandates fail

### ISSUE THREAD

**Issue by jdelos** [mollie/mollie-api-python#154]
**Get mandates not working**

**Issue** this function only takes one parameter, the `mandate_id`. 
You cannot pass the `customer_id` as a parameter, then the API request fails because is missing the `customer_id`.

` mollie_client.customer_mandates.get(...) `

I made this workaround

```
def get(self, mandate_id, customer_id,**params):
        if not mandate_id or not mandate_id.startswith(self.RESOURCE_ID_PREFIX):
            raise IdentifierError(
                "Invalid mandate ID: '{id}'. A mandate ID should start with '{prefix}'.".format(
                    id=mandate_id, prefix=self.RESOURCE_ID_PREFIX)
            )

        self.customer_id = customer_id
        return super().get(mandate_id, **params)
```

I hope you can fix it soon

**Comment by whyscream** [comment]
To retrieve a list of customer mandates for a specific customer, you need to do:
```
client.customer_mandates.with_parent_id(CUSTOMER_ID).list()
```
For a single mandate, you need:
```
client.customer_mandates.with_parent_id(CUSTOMER_ID).get(MANDATE_ID)
```

Another way to retrieve a customer mandate is to use a Customer object:
```
customer = client.customers.get(CUSTOMER_ID)
client.customer_mandates.on(customer).get(MANDATE_ID)
```

@jdelos I hope this helps?

**Comment by whyscream** [comment]
I believe this is merely a documentation issue, and it needs no patch in the package code.
Closed until a response is received.
