### ISSUE TITLE
AttributeError: Client instance has no attribute 'customers'

### ISSUE THREAD

**Issue by michaelshmitty** [mollie/mollie-api-python#16]
Either this python package is broken or the [documentation here](https://www.mollie.com/nl/docs/reference/customers/list) is wrong:

`import Mollie`
`mollie = Mollie.API.Client()`
`mollie.setApiKey('test_...')`
`>>> mollie.customers.all()`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
`AttributeError: Client instance has no attribute 'customers'`

I noticed a [similar issue](https://github.com/mollie/mollie-api-ruby/issues/34) with the [mollie-api-ruby gem](https://github.com/mollie/mollie-api-ruby).

Are any of the [Mollie-modules](https://www.mollie.com/nl/modules) actually maintained?

**Comment by mollierobbert** [comment]
Thanks for notifying us, Michael. Our Python and Ruby clients have become a bit outdated with new API endpoints that were introduced with our Recurring product (Customers API, Mandates API, Subscriptions API). We'll upgrade the API clients in a few weeks.

Of course, if you're in a hurry, feel free to open a pull request to add these endpoints.

**Comment by Lexstok** [comment]
Do I need to upgrade my donation page that used your client example (Python Flask) as well then ?

**Comment by michaelshmitty** [comment]
Thanks for the reply, @mollierobbert. Hopefully the clients can be made part of the release of new API features in the future so this confusion can be avoided.

I'm sure you meant well with your last remark, but I think it's important to clear this up: Mollie's client libraries are not free, community open source projects as the copyright statements and the license text in general indicates.
So asking Mollie's customers to implement fixes and issue pull requests is a bit of a weird logic.
As is assuming your customers have the expertise and time to spare to do this. They are busy building their own application to interface with your service. So I believe it's in Mollie's best interest to keep these libraries up to date with new API releases.
Thanks for listening and good luck.

**Comment by mollierobbert** [comment]
Thanks for voicing your concerns with our copyright statements, Michael.

Our Python and Ruby clients simply aren't popular enough to have them on the top of our priority list when we add new API features. Upgrading them is definitely on our roadmap though, as stated earlier.

**Comment by mollierobbert** [comment]
@Lexstok I'm unsure whether this issue applies to you too. Did you experience the same issue with our missing Customers endpoint?

**Comment by vte** [comment]
@mollierobbert Will the python client be updated anytime soon? We ran into the same issue, but want to use Mollie for recurring payments through python.

**Comment by robin-mollie** [comment]
@vte We're looking into updating our api clients at the moment. This is one of the issues that will be taken into account for the next version :)

**Comment by vincentleeuwen** [comment]
@robin-mollie @mollierobbert Same here, any updates on this or PR #17 ? Thanks!

**Comment by Pimm** [comment]
@michaelshmitty @vte @vincentleeuwen FYI: PR #17 has been merged just now.

**Comment by FaaPz** [comment]
Closing. Already solved in the latest release: **v1.2.0** (33a2b6702739901f884f88edf7b8be25304cc2e5)
