### ISSUE TITLE
Different redirectUrl for returning to page than after payment

### ISSUE THREAD

**Issue by LaundroMat** [mollie/mollie-api-python#177]
Is it possible to have a different URL for the "back to site" link on the payment page than the one the user is redirected to after doing the payment?

I would like to show a different message to the user after they have submitted a payment than when they click the 'back to site' link on the payment page (the link in the bottom left of this screen:)

![image](https://user-images.githubusercontent.com/42320/96878961-bd09c880-147b-11eb-9731-00a230b476ab.png)

**Comment by whyscream** [comment]
Hi @LaundroMat ,

The redirect URL is always the same, independent of the payment result.
If you want to do anything smart depending on the transaction, you application should query the mollie API when the the user hits the redirect URL.

This is also documented at https://docs.mollie.com/payments/overview#how-does-the-payments-api-work:
- step 4 is the redirect from Mollie back to your website
- step 5 is where your application queries mollie for the payment status.

**Comment by LaundroMat** [comment]
Oh I get it now! Thanks :) -- I'll close this issue.
