### ISSUE TITLE
Prevent requests timing out

### ISSUE THREAD

**Issue by rares-mollie** [mollie/mollie-api-python#178]
See: https://github.com/mollie/mollie-api-php/issues/498

As per the issue in the mollie-api-php repository, we have found that a number of clients are experiencing request timeouts due to unreliable domain name resolution, this happens due to UDP based resolution on the client side and is completely out of our control. Mollie has taken all necessary steps to ensure that it is serving DNS queries from the most reliable providers but in synthetic tests a small amount of UDP based queries still fail.

In order to prevent failed requests and make the client robust against other kinds of client-side and Mollie-side connection issues as well, we want to implement a retry mechanism that addresses connect-time errors only, with configurable timeouts, retries and back-off strategy, similar in functionality to the one implemented in the PHP API via https://github.com/mollie/mollie-api-php/pull/499

**Comment by whyscream** [comment]
@rares-mollie functionality added in #182. Will be released as v2.5.0
