### ISSUE TITLE
OAuth2Session initialization

### ISSUE THREAD

**Issue by foarsitter** [mollie/mollie-api-python#188]
In a multi worker environment the global variable (as used in the examples) is not shared across workers. Therefore, the OAuth client needs to be initialized each request. 

Currently the initialization of the OAuth2Session is embed in the setup_oauth method and cannot be used in a DRY way.

**Comment by whyscream** [comment]
Hi @foarsitter , thanks for submitting a PR. We'll look into it.

**Comment by whyscream** [comment]
Hi @foarsitter,

I'm trying to understand the problem you're trying to solve. The example is just that: an example. In a multi-worker environment you should not use a global variable, but initialize the client in each worker.

I'm also failing to see how your proposed change should resolve your problem. Could you please elaborate?

**Comment by foarsitter** [comment]
The proposed change makes it easier to initialize the client be separating the `authorization_url` part and the initialization of the `OAuth2Session`. 

This makes it possible to call `client.init_oauth_client(*args,**kwargs)` and `client.payments.create(*args, **kwargs)` afterwards without the need of a custom initialization method to setup an `OAuth2Session`.

In terms of the [invoices](https://github.com/mollie/mollie-api-python/blob/master/examples/oauth/01-invoices.py) example, discarding the client parameter, this results in the following coding flow:
```python
client = Client()
client.init_oauth_client(*args, **kwargs)
client.invoices.list()
```

Of-course it is even better to create a factory method to inject the correct values to `init_oauth_client`. I can update the examples this way if you like.

**Comment by foarsitter** [comment]
As pointed out by @whyscream the `setup_oauth` method does not invoke any requests when authorized is True. So `setup_oauth` can be used in the same way as my proposed `init_oauth_client`. Therefore this issue can be closed.
