### ISSUE TITLE
Wrong endpoint url in subscription_payments resource

### ISSUE THREAD

**Issue by wandura** [mollie/mollie-api-python#190]
https://github.com/mollie/mollie-api-python/blob/282541b25fa83eae0eb9f1a3798a080b759dcf38/mollie/api/resources/subscription_payments.py#L9

The correct api endpoint must have "subscriptions" with "s".
I get an error message with the current endpoint url:
`mollie.api.error.NotFoundError: Invalid resource endpoint`

**Comment by whyscream** [comment]
We just released v2.5.3 of the client which resolves this issue. Thank you for reporting.
