### ISSUE TITLE
Suggestion: add type-hints

### ISSUE THREAD

**Issue by whyscream** [mollie/mollie-api-python#192]
Adding type hints (https://www.python.org/dev/peps/pep-0484/, https://docs.python.org/3/library/typing.html) helps developers to check their code. It also assists various code editors that use the hints for autocompletion and error checking. Kindly suggested by  @foarsitter.

**Comment by foarsitter** [comment]
Nice work, didn't realize python 3.6 is EOL so soon.

**Comment by whyscream** [comment]
Typehints for a major part of the code were added in v3 (release candidate available as of today). We'll continue to add more hints as we touch other code. Closing this for now.
