### ISSUE TITLE
Payment Links

### ISSUE THREAD

**Issue by adrijanb** [mollie/mollie-api-python#196]
Hey,
Today i wanted to implement some new features to our billing. I have found out, that mollie's api can now create payment links. Could you implement this or do you have any ETA already?

**Comment by whyscream** [comment]
hi @adrijanb 

We'll look into this on a short term. Thanks for the heads up

**Comment by whyscream** [comment]
https://docs.mollie.com/changelog/v2/changelog#friday-2nd

**Comment by adrijanb** [comment]
Yes, exactly. I might need this endpoint. It would be really helpful for me and my customers😅
Am 14. Juni 2021, 12:02 +0200 schrieb Tom Hendrikx ***@***.***>:

**Comment by whyscream** [comment]
@adrijanb We have just released version 2.9.1 of the library, with support for Pyament Links. Thank you!
