### ISSUE TITLE
Why is there no amount_chargedback property

### ISSUE THREAD

**Issue by bruecksen** [mollie/mollie-api-python#210]
Hello,

I'm wondering why there is no `amount_chargedback` property in the payment object class which should be similar to the `amount_refunded` property which is there? Is there a reason for that? It would be nice to have this optional value available in the python api as well. I could open a PR for that if wanted.

```
@property
    def amount_chargedback(self):
        return self._get_property("amountChargedBack")
```

**Comment by andreashug** [comment]
I'd also consider this really helpful. In addition a `has_chargebacks()` method similar to `has_refunds()` would be great.

**Comment by bruecksen** [comment]
@andreashug yes, that's what i thought as well. Will add a PR soon.

**Comment by whyscream** [comment]
Hello @bruecksen and @andreashug , We can add that property indeed. No idea why we missed that up to now.
