### ISSUE TITLE
Payment is created and open, but not completed

### ISSUE THREAD

**Issue by FurkanSimsir** [mollie/mollie-api-python#23]
Hi, I want to implement Mollie iDeal in my Python/Django app. I can get to the part where a payment is created, but I don't know how to complete it. I'm using Postman for my POST requests for now, but it has to be implemented in my food ordering iOS app as well. 

             import Mollie
             from bestel.settings import MOLLIE_API_KEY

             mollie = Mollie.API.Client()
             mollie.setApiKey(MOLLIE_API_KEY)
             order_nr = int(time.time())

            payment = mollie.payments.create({
            'amount':      order_total,
            'description': 'My first API payment',
            'webhookUrl':  'http://localhost:8000/' + '2-webhook-verification?order_nr=' + str(order_nr),
            'redirectUrl': 'http://localhost:8000/' + '3-return-page?order_nr=' + str(order_nr),
            'metadata': {
                'order_nr': order_nr
            },
            'method': 'ideal',
            'issuer': issuer_id,  # e.g. 'ideal_INGBNL2A'
            })

            if payment.isPaid():
                # Step 2 - Create an Order
                order = Order.objects.create(
                    customer = customer,
                    restaurant_id = request.POST["restaurant_id"],
                    total = order_total,
                    status = Order.COOKING,
                    address = request.POST["address"]
                )

                # Step 3 - Create Order details
                for meal in order_details:
                    OrderDetails.objects.create(
                        order = order,
                        meal_id = meal["meal_id"],
                        quantity = meal["quantity"],
                        sub_total = Meal.objects.get(id = meal["meal_id"]).price * meal["quantity"]
                    )

                return JsonResponse({"status": "success"})
            else:
                return JsonResponse({"status": "failed", "error": "Failed connect to Mollie."})

However the status is failed so I the "order" (step 2&3) is not being created in Django.

Can anyone help me further?

**Comment by willemstuursma** [comment]
Hi @FurkanSimsir. For these kind of questions, you can best contact our support department at info@mollie.com. It does not seem to be a problem with the API client per se.
