### ISSUE TITLE
Checkout URL in test mode refers to credit card

### ISSUE THREAD

**Issue by yannicschroeer** [mollie/mollie-api-python#261]
Hello,

we encounter issues with the test mode using this python API client. Some time ago we used the same code and it worked perfectly, but since a few weeks the test mode screen as described here: https://docs.mollie.com/overview/testing is no longer available when using the checkout url of initiated payments. 

## Problem description

This is the code we are using to obtain the first payment of a future series of background payments:

```python
payments.create({
  'amount': {
    'currency': 'EUR',
    'value': '0.00' 
  },
    'customerId': 'cst_123456',
    'sequenceType': 'first', 
    'locale': 'de_DE',  
    'description': 'Some title',  
    'webhookUrl': 'https://example.com/webhook',  
    'redirectUrl': 'https://example.com/redirect'
  }
)
```

We use a test API key to perform this client library request.

### Expected behaviour

We get a checkout URL like `https://www.mollie.com/checkout/UomV7nXHTb` in `_links.checkout` in the response object, to simulate a checkout with whatever parameters we choose (Set it to `open`, `paid` etc.)

### Actual behaviour

We get a URL of the form `https://www.mollie.com/checkout/credit-card/embedded/UomV7nXHTb` in the `_links.checkout` which refers to a page that uses credit card as the preconfigured payment method. If we use the navigation to navigate to the payment methods we get redirected to the provided `redirect_url`.

I also downgraded the api client to an older version to avoid api client related defaults as the cause but it seems not to resolve the issue.

## Question

How do we get the generic `checkout_url` again that provides the test mode checkout screen documented here: https://docs.mollie.com/overview/testing

Thank you in advance

**Comment by JorikMollie** [comment]
Hi Yannic,

This change is behaviour of the test environment is an unintended consequence of a change to the Mollie platform that we rolled out.

You can fill in any card details that pass the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) and an expiry date in the future. In practice: it is faster to Google "test credit card numbers".

I've created a ticket for our development team to restore the original behaviour.

**Comment by yannicschroeer** [comment]
Thank you for your response! Could you please let me know here when the ticket has been processed?

**Comment by JorikMollie** [comment]
Will do!

**Comment by whyscream** [comment]
@JorikMollie any news on this?

**Comment by JorikMollie** [comment]
So far no updates, it has not been included in a sprint so far.

**Comment by whyscream** [comment]
Seems to be resolved, according to https://github.com/mollie/mollie-api-php/issues/648
