### ISSUE TITLE
Removal subscription_id from payment object.

### ISSUE THREAD

**Issue by WAKayser** [mollie/mollie-api-python#292]
In the v3 release the property "subscription_id" was removed from the payment object in:
https://github.com/mollie/mollie-api-python/commit/de6d18b634fbe2ab0cc7b6e09583547624003037#diff-a5e223df1e7a00bf1df026fc64bdc4a5e26bb330fae58c0689eca041070eb5db

Is there a new preferred method of getting just the subscription id from a payment object?

**Comment by whyscream** [comment]
Hi @WAKayser,

This is a bug. In https://docs.mollie.com/reference/v2/payments-api/get-payment#response-parameters-for-recurring-payments the subscription_id is a documented property. We'll add it back

**Comment by whyscream** [comment]
Resolved in #293 and [Release 3.0.1](https://github.com/mollie/mollie-api-python/releases/tag/3.0.1). Thanks for reporting, @WAKayser
