### ISSUE TITLE
Django app example

### ISSUE THREAD

**Issue by talatozmusluman** [mollie/mollie-api-python#305]
Hi, 
Could you please provide an example or provide any guideline for Django payment integration?

**Comment by whyscream** [comment]
Hi @talatozmusluman,

As Django has no specifics for payment handling, and this package has no specific code targeting Django, most of this would be up to yourself (Django is not an ecommerce platform where it would be obvious where to add a payment provider). There are some projects on Github to integrate Mollie with various Django-based solutions (f.i. Oscar Ecommerce), but none of these seem to be well-maintained. 

Some time ago we started working on [a new Django + Mollie integration](https://github.com/fourdigits/django-payments-mollie) based on [Django Payments](https://django-payments.readthedocs.io/). It provides all of the important parts: a view where you can start a payment and get redirected to Mollie, a database model to store the payments and the Mollie responses, and a callback endpoint where Mollie can post you results.

All of that is very basic, and not used in production anywhere (AFAIK). Despite what the README says, only API KEY authentication is working for now, and there's no package on PyPI yet, so you'll need to install from the github repo. If you want to try it, feel free to do so. Please leave any issues or remarks that you find in the [issue tracker of the project](https://github.com/fourdigits/django-payments-mollie/issues).

**Comment by whyscream** [comment]
Hi @talatozmusluman,

As Django has no specifics for payment handling, and this package has no specific code targeting Django, most of this would be up to yourself (Django is not an ecommerce platform where it would be obvious where to add a payment provider). There are some projects on Github to integrate Mollie with various Django-based solutions (f.i. Oscar Ecommerce), but none of these seem to be well-maintained. 

Some time ago we started working on [a new Django + Mollie integration](https://github.com/fourdigits/django-payments-mollie) based on [Django Payments](https://django-payments.readthedocs.io/). It provides all of the important parts: a view where you can start a payment and get redirected to Mollie, a database model to store the payments and the Mollie responses, and a callback endpoint where Mollie can post you results.

All of that is very basic, and not used in production anywhere (AFAIK). Despite what the README says, only API KEY authentication is working for now, and there's no package on PyPI yet, so you'll need to install from the github repo. If you want to try it, feel free to do so. Please leave any issues or remarks that you find in the [issue tracker of the project](https://github.com/fourdigits/django-payments-mollie/issues).

**Comment by whyscream** [comment]
Closing, no response
