### ISSUE TITLE
Is partial refund supported?

### ISSUE THREAD

**Issue by piqoni** [mollie/mollie-api-python#31]

**Comment by mvdpanne** [comment]
It is supported, by adding a `data` parameter for the function call, for example:
`
client = Mollie.API.Client()
client.payments.refund(payment, {"amount": 10})
`

This might be kind of confusing, given that for other methods, the behavior is like this:
`
client.payments.all(count=20)
`

The key here is that POST requests use the first syntax, GET requests the second. This will be corrected in the next release, such that all calls can make use of keyword arguments.
