### ISSUE TITLE
The payment status is not the same as in Mollie's web dashboard account.

### ISSUE THREAD

**Issue by nikolaysm** [mollie/mollie-api-python#310]
The transaction was charged back, but through the API we still get the status "paid". How can we get the right transaction status?

**Comment by fjbender** [comment]
Hi @nikolaysm,

This sounds like unusual behavior. However, it has nothing really to do with the Python API Client. May I ask you to contact our [support team](https://www.mollie.com/gb/contact/merchants), please? They'll be able to help you find out what happened to your payment exactly, and can advise you on how to handle those cases in the future.

Thanks
Florian

**Comment by fjbender** [comment]
Just for clarification, as I might have misunderstood/over-interpreted your question: Does `payment.has_chargebacks()` return `True` or `False` for you on that particular payment?

In our API, payments remain `paid`, but get a `chargeback` object attached to them.

**Comment by nikolaysm** [comment]
Hi @fjbender,

Yes, `payment.has_chargebacks()` does return `True`. 

Why don't we get the same statuses through the API?:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3074155/229737178-e1616c7f-5dda-4a64-9754-0f3443258ad5.png">


According to [API docs](https://docs.mollie.com/payments/status-changes), the status can have the following values: `["open", "canceled", "pending", "authorized", "expired", "failed", "paid"]`.

And how about the following values?:
```
CHARGEBACK = "chargeback" -> payment.has_chargebacks()
REFUNDED = "refunded"  - > payment.has_refunds()
SETTLED = "settled" - > bool(payment. settlement_id) ?
PARTIALLY_REFUNDED = "partially-refunded"  - > ????
REFUND_PROCESSING = "refund-processing"  - > ????
BLOCKED = "blocked" - > ????
```

Thanks,
Nikolay

**Comment by nikolaysm** [comment]
It is not clear to me, why Mollie doesn't provide the same status through the API as it used in Mollie's web dashboard?

Through the Mollie's internal API you can get the right status:
```
{
  "resource":"payment",
  "id":"tr_xxxxxx",
  "mode":"test",
  "createdDatetime":"2023-04-xxxxxxx",
  "status":"charged_back" ⬅️⬅️⬅️⬅️⬅️⬅️⬅️⬅️⬅️⬅️⬅️⬅️⬅️
  ...
}
```

**Comment by fjbender** [comment]
The [Payment State Machine](https://docs.mollie.com/payments/status-changes#how-does-one-status-lead-to-another) is very simple and doesn't contain all statuses listed above.

The other statuses you list are not part of that state machine, but rather properties of the payment in general. This is why the Python API Client provides you with shortcuts like `payment.has_chargebacks()`. A similar approach is used to prepare data to be displayed in the Dashboard, which is why you see that status there but not on the Payments API.
