### ISSUE TITLE
Not providing `method` in payment parameters in test mode breaks pending/cancel/failed/expired flow

### ISSUE THREAD

**Issue by ideallical** [mollie/mollie-api-python#318]
I'd like to create a flow where the payment method is chosen inside Mollie, hence I leave out the `method` argument when creating a payment as described here: https://docs.mollie.com/reference/v2/payments-api/create-payment

However, when I do this in test-mode, the `pending`, `cancel`, `failed` & `expired` flow, all redirect to the "choose payment" screen, instead of the provided `redirectUrl`.

The redirect on cancel, pending, failed & expired does work when I provide for example `method="ideal"`

Am I forgetting something or is this is Bug in the test environment of Mollie?

I'm using **mollie-api-python = "^2.13.0"**

**Comment by JorikMollie** [comment]
Hi @ideallical ,

When a consumer does not complete the payment with their chosen payment method they are redirected to the payment method selection screen. This way the consumer can try again with another payment method.

On the payment method selection screen you can find a "back to website button" at the bottom. Clicking this button will cancel the payment and redirect the consumer to the `redirectUrl`.

Our test and live environments exhibit the same behaviour.

Let me know if you have any additional questions!

**Comment by ideallical** [comment]
I see now, thanks for clarifying that!
