### ISSUE TITLE
01-new-payment-using-qrcode is broken

### ISSUE THREAD

**Issue by hlgrondijs** [mollie/mollie-api-python#345]
To reproduce:

- Install this repository according to instructions (`python -m venv .venv` and onwards), then run with `python examples/app.py`. 

- Open browser and click on the example [01-new-payment-using-qrcode](http://localhost:5000/01-new-payment-using-qrcode)

- Get error

```
qr_code = payment.details["qrCode"]
TypeError: 'NoneType' object is not subscriptable
```
-------------------------------

I have the same error in my own code. `payment.details` is `None`. How do I access my qrCode and please update the example code.

**Comment by fjbender** [comment]
Good catch, thanks! For the QR code to work, the `method` must be set to either `ideal` or `bancontact`, see the [create payment docs](https://docs.mollie.com/reference/create-payment). I have updated the example accordingly.
