### ISSUE TITLE
from . import Object ImportError: cannot import name Object

### ISSUE THREAD

**Issue by semirturgay** [mollie/mollie-api-python#36]
Hi I got the following error after installing this package : 

``` 
import Mollie
  File "/Users/semirturgay/Desktop/Dev/default/lib/Mollie/__init__.py", line 3, in <module>
    from . import API
  File "/Users/semirturgay/Desktop/Dev/default/lib/Mollie/API/__init__.py", line 3, in <module>
    from . import Object
ImportError: cannot import name Object 
```
The python version : 2.7.14

**Comment by mvdpanne** [comment]
Hey Semir,

After doing a clean install of the `mollie-api-python` package through `pip` on Python 2.7.14 I see no such error when executing `import Mollie`. So I am unsure what the problem might be.

If you could let me know how you installed the package, and how/where you are importing the `Mollie` package, I could perhaps help you further. I suppose the only thing you are trying to do is `import Mollie`? If there is more to it, then please provide example code that fails on your side.

Are you on the latest version of the `mollie-api-python` package (v1.3.1)?

**Comment by semirturgay** [comment]
Hey @mvdpanne, 
I solve my problem it was because of i was installing the package to a folder
`pip install mollie-api-python -t lib/`
since you have a dependency to `pck_source` i did also 
`pip install install -U setuptools -t lib/` 
then it worked.

**Comment by mvdpanne** [comment]
Hey Semir,

Good to hear that you were able to solve the problem. I will close this issue now.
