### ISSUE TITLE
The currency 'GBP' is not supported.

### ISSUE THREAD

**Issue by Mark-2445** [mollie/mollie-api-python#366]
Hi, 

I am trying to setup a new payment with Mollie (in test mode) and I keep getting 'The currency 'GBP' is not supported.' when trying to make a payment link. 

I've attached my JSON data below, this is being sent in the mollie_client.payment_links.create() event. 

``` json
{
    "description": "test item",
    "amount": {
        "currency": "GBP",
        "value": "10.00"
    },
    "webhookUrl": "<my webhook url here>",
    "redirectUrl": "<my redirect url here>",
    "expiresAt": "2024-10-06T11:00:00+00:00",
}
```

**Comment by Mark-2445** [comment]
I only have Cards & Apple Pay enabled, would Apple Pay be blocking this? 

The docs state 'Currencies supported for card payments are generally also available for other card-based payment methods, such as Apple Pay.'

**Comment by fjbender** [comment]
Hi @Mark-2445, this might be an issue with your Mollie account instead of an issue with the Python package. I advise to reach out to our support team, they'll be able to check this out for you.

Thanks!
