### ISSUE TITLE
No implementation for some api calls  

### ISSUE THREAD

**Issue by semirturgay** [mollie/mollie-api-python#37]
Hi.
I need to create subscriptions for recurring payments but it seems there are no implementations on mollie client for some methods ; 

`mollie.customers_subscriptions`
`mollie.customers_mandates`

is it possible for you to implement them. 
Thanks.

**Comment by willemstuursma** [comment]
Hi @semirturgay! If you really need this really fast, you can provide a PR and we'll look at it, provide you with feedback en eventually release a new version.

Else, we'll pick it up in a few weeks. 

I'm sorry this is missing in our API client.

**Comment by semirturgay** [comment]
@willemstuursma ok i will try to open a pr tomorrow.

**Comment by Meteor0id** [comment]
Hoping to see this soon. We have a startup organization with a public campaign which needs to be on schedule and we depend on donations. Reoccurring payments make a big difference to us, and we do need it fast unfortunately. (have no time to run the start-up and make the commit)

**Comment by mvdpanne** [comment]
I think that at this point in time, the mentioned endpoints are part of the API client. If there are still problems, feel free to place additional comments in this issue.

For now, I will close the issue.
