### ISSUE TITLE
Provide example of qrcode

### ISSUE THREAD

**Issue by judgewooden** [mollie/mollie-api-python#38]
The documentations says: Some endpoints allow you to indicate if you want more information to be included in the API response via the include querystring parameter.

But it is unclear how the querystring is changed during the mollie.payments.create method or how the response is processed in Flask to get the qrcode to show to the user.

**Comment by mvdpanne** [comment]
Hello,

This is now fixed in release `v1.4.0`. Please see the updated `README.md`, which shows an example of retrieving a QR code along with a newly created payment.

The QR code object is returned in the API call response, under the `qrCode` key. So, you can retrieve the QR code object as follows:
```python
payment = mollie.payments.create( ... )
qr_code = payment['qrCode']
```
