### ISSUE TITLE
Support for API v2

### ISSUE THREAD

**Issue by alexandervlpl** [mollie/mollie-api-python#40]
It would be great to see support for the v2 API (specifically, the multicurrency option).

**Comment by Meteor0id** [comment]
At this rate, let's skip to v3? Python seems to be a very low priority to Mollie.
bit frustrated about that, since the python API is not vey suefull withotu support for reoccuing payments (api v1) and custom currency (api v2).

**Comment by mvdpanne** [comment]
The last couple of weeks, a lot of work has been put into releasing a new version of the Python API client that has support for our V2 API, has proper tests and is in general a big improvement over the current implementation.

We're close! You can view the progress in PR #45.

**Comment by alexandervlpl** [comment]
@mvdpanne : thanks for working on this, really appreciated!

For anyone else who needs a Python solution now, my [Gist](https://gist.github.com/alexandervlpl/4c6ec764403f8bcc39d873d1e1e75a32) might save you time.

**Comment by mvdpanne** [comment]
Version 2.0.0 of the Mollie API client has now been released, which adds support for the v2 API! 🎉
