### ISSUE TITLE
How to set currency while creating payments using mollie.payments.create({})

### ISSUE THREAD

**Issue by sudheerkdty** [mollie/mollie-api-python#41]
I was trying to create a payment using mollie
```
payment = mollie.payments.create({
                                     'amount': amount,
                                     'description': description,
                                     'redirectUrl': base_url + reverse('payment_validate_url', kwargs={'id': order_id}),
                                     'customerId': user.userprofile.mollie_id,
                                     'webhookUrl': webhook_url,
                                     })
```
I wanted to set a currency. But I found no method for it. 
https://docs.mollie.com/reference/v2/payments-api/create-payment

**Comment by Smitsel** [comment]
Hi, thats not possible at the moment.
The currency bit is part of our new v2 api and the python client does not support this yet.
Our v1 api only works with EUR so you cannot set a currency yet.

You can watch issue #40 for the update to v2.

**Comment by alexandervlpl** [comment]
@sudheerkdty : you can always make requests to the v2 API directly. My example:
https://gist.github.com/alexandervlpl/4c6ec764403f8bcc39d873d1e1e75a32
