### ISSUE TITLE
Overview of changes between releases

### ISSUE THREAD

**Issue by wrvdklooster** [mollie/mollie-api-python#56]
We are using this API in a project for a large customer.

Although I like to keep up with recent releases of libraries I decided not to switch to 1.4.2 because I have no idea what changes are done.

Can you add a change log indicating what changes are made between release?

Thx!

**Comment by Smitsel** [comment]
Hi @wrvdklooster,

The release was very minor. I've just updated the release description with all the changes:
https://github.com/mollie/mollie-api-python/releases/tag/v1.4.2

What version are you on now?

**Comment by wrvdklooster** [comment]
Hi, we are now in v1.4.1 so indeed the changes are minimal. I normally check a history / changes file and overlooked the releases. Sorry for that.

All fine, will upgrade.

Thx!
