### ISSUE TITLE
Unknown field: Currency

### ISSUE THREAD

**Issue by Boai12** [mollie/mollie-api-python#57]
Hey there,

I've been trying the module out but when creating a simple payment I get the following stacktrace:
```
G:\pythonENV\mollie\Scripts\python.exe G:/mollie/App.py
Traceback (most recent call last):
  File "G:/mollie/App.py", line 14, in <module>
    'webhookUrl': 'https://webshop.example.org/mollie-webhook/',
  File "G:\pythonENV\mollie\lib\site-packages\Mollie\API\Resource\Base.py", line 54, in create
    return self.rest_create(data, params)
  File "G:\pythonENV\mollie\lib\site-packages\Mollie\API\Resource\Base.py", line 26, in rest_create
    result = self.performApiCall(self.REST_CREATE, path, data, params)
  File "G:\pythonENV\mollie\lib\site-packages\Mollie\API\Resource\Base.py", line 83, in performApiCall
    raise error
Mollie.API.Error.Error: Error executing API call (request): Unknown field: currency.
```
```
from Mollie.API.Client import Client

mollie_client = Client()
mollie_client.setApiKey('test_MY_KEY')

Code:
payment = mollie_client.payments.create({
    'amount': {
        'currency': 'EUR',
        'value': '10.00'
    },
    'description': 'My first API payment',
    'redirectUrl': 'https://webshop.example.org/order/12345/',
    'webhookUrl': 'https://webshop.example.org/mollie-webhook/',
})
```

Got no clue what the problem might be, I checked the API and read the read.me but have no idea.

**Comment by Lexstok** [comment]
is your website really webshop.example.org ? That might be part of the problem...

**Comment by willemstuursma** [comment]
I think the API request is still sent to the v1 API. 

We've got a beta of the client that will go to v2. Unfortunately, we're still working on creating the release but you can clone the master branch of course.

**Comment by Boai12** [comment]
I've got mollie-api-python 1.4.2 installed trough pycharm. Trying to install tough the command line with no succes yet :( I'm new to python

**Comment by Boai12** [comment]
I got it working, thank you. (Installing from the master did the trick)

**Comment by mvdpanne** [comment]
Good to hear that you got it working 👍 I will close this issue now.
