### ISSUE TITLE
Functionality for unit testing

### ISSUE THREAD

**Issue by mbtronics** [mollie/mollie-api-python#58]
Hi,

I'm trying to unit test a python application that uses mollie.
Is there any possibility for using the library in a unit test without access / valid key?
Are there any mocks?

If I write basic mocking functionality myself, is there a chance to get it included?

**Comment by mvdpanne** [comment]
Hi mbtronics,

When testing your application, you should be able to mock the Mollie API client just fine with the [built-in libraries](https://docs.python.org/3/library/unittest.mock.html). The client does not require an actual valid api key. It only needs to start with `test_` or `live_`. Only when outgoing calls are made, the key will be validated.

Mocking functionality is not a responsibility of the API client, and therefore won't be included in the repository.
