### ISSUE TITLE
Installation example master branch

### ISSUE THREAD

**Issue by KDederichs** [mollie/mollie-api-python#59]
I just ran into the issue that the pip installation example on the master branch in fact installs the version pushed in v1-develop (which obviously didn't work because that one is very different).
You might want to label that accordingly on the master branch or maybe even make a new one for the V2 API on master?

**Comment by mvdpanne** [comment]
Hi KDederichs,

Thank you for letting us know that the installation instructions were unclear. I have just updated them in both branches, including an example of how to install the master branch through `pip`.
