### ISSUE TITLE
CA Certs

### ISSUE THREAD

**Issue by nelsonvarela** [mollie/mollie-api-python#8]
I'm not feeling comfortable with the idea that the CA-bundle is almost 3 years old...?

Why not let requests handle this and use verify=True?

**Comment by mollierobbert** [comment]
Nelson, we're supplying the `cacert.pem` to make installation easier for our merchants, some of which may not have configured their servers properly or do not even understand how PKI works.

Of course as a power user, you're free to fork and make the desired changes.

**Comment by mollierobbert** [comment]
We've updated the bundle in https://github.com/mollie/mollie-api-python/commit/de536eb3f64804431a2ee28ca997fabe6a1a4455.

**Comment by rudolphfroger** [comment]
I think this is a serious issue, Mollie doesn't seem to be the correct party to keep a PKI bundle up-to-date at all times. To me this seems like a task for a distributor of an operating system and/or a web browser.

The solution is easy and also solves Robberts' concern: only include the strictly required CA certificates in the bundle (I assume Mollie only uses one or possibly a few CA's for their API). In that solution Mollie only needs to update the bundle when its CA hands out new root/intermediate certificates.
