### ISSUE TITLE
Use certifi package for verifying the certificate

### ISSUE THREAD

**Issue by whyscream** [mollie/mollie-api-python#81]
Current code bundles a vendored list of CA certificates for verification of the Mollie API SSL cert. This bundle needs updating once in a while, and might force users of an older package to upgrade only because the certificate bundle.

We should use the external package `certifi` (https://pypi.org/project/certifi/) to verify certificates. We already install the package as it's a dependency of `requests`.

**Comment by martijnpolder** [comment]
I reviewed the package, it seems legit and accurately maintained. I'm greenlighting the use of this package to improve on our current CA update process.
