### ISSUE TITLE
Setup.py doesn't list dependencies

### ISSUE THREAD

**Issue by rudolphfroger** [mollie/mollie-api-python#9]
Hi, this library depends on the Python requests library, please add this to the dependencies in setup.py.

    install_requires=["requests"]

**Comment by nelsonvarela** [comment]
I worked on this on #7 .

**Comment by mollierobbert** [comment]
Merged in https://github.com/mollie/mollie-api-python/commit/20e3853c718ec57cdbdb7dddd6092af1e3659b4e.
